Added EE countries for cmp
AutoScout24/showcar-tracking pull request #50
Opened 2020-09-03 15:48 UTC by fabianScout

2020-09-04 08:45 UTC, bdadam requested changes

2020-09-04 08:45 UTC, bdadam commented on src/cashstack.js
> +        bg: 'GTM-KWX9NX',
We already have com as fallback:
```js
const containerId = containerIdsByTld[tld] || containerIdsByTld['com'];
```

2020-09-04 08:45 UTC, bdadam commented on dist/index.html
> +        var releasedCountries = ['at', 'be', 'com', 'de', 'es', 'fr', 'nl', 'lu', 'it', 'bg', 'cz', 'ru', 'pl', 'hu', 'hr', 'ro', 'se', 'tr', 'ua'];
No need for this line and the if statement below anymore. With this PR the CMP will be released on all domains.

2020-09-04 08:45 UTC, bdadam commented on dist/index.html
> +                    var releasedCountries = ['at', 'be', 'com', 'de', 'es', 'fr', 'nl', 'lu', 'it', 'bg', 'cz', 'ru', 'pl', 'hu', 'hr', 'ro', 'se', 'tr', 'ua'];
Same as above, no need to check for `releasedCountries` anymore.

2020-09-04 08:45 UTC, bdadam commented on src/cashstack.js
> +    var releasedCountries = ['at', 'be', 'com', 'de', 'es', 'fr', 'nl', 'lu', 'it', 'bg', 'cz', 'ru', 'pl', 'hu', 'hr', 'ro', 'se', 'tr', 'ua'];
Same as above.

2020-09-07 08:17 UTC, fabianScout commented on dist/index.html
> +        var releasedCountries = ['at', 'be', 'com', 'de', 'es', 'fr', 'nl', 'lu', 'it', 'bg', 'cz', 'ru', 'pl', 'hu', 'hr', 'ro', 'se', 'tr', 'ua'];
fixed

2020-09-07 10:57 UTC, bdadam approved these changes

2020-09-07 10:57 UTC, merged